apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsbootcamp-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:  
  rules:
  - host: "kubernetes.docker.internal"
    http:
      paths:
      - path: /app1/goku
        pathType: Prefix
        backend:
          service:
            name: devopsbootcamp-app
            port: 
              number: 80
