apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appname.name }}
  namespace: {{ .Values.appname.name }}
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    name: {{ .Values.appname.name }}
    kind: Deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageUtilization }}